const sb=window.supabase.createClient(CF_CONFIG.supabaseUrl,CF_CONFIG.supabaseKey); window.CF={sb};
const continents={
 Africa:['Algeria','Angola','Benin','Botswana','Burkina Faso','Burundi','Cabo Verde','Cameroon','Central African Republic','Chad','Comoros','Congo','Democratic Republic of the Congo','Djibouti','Egypt','Equatorial Guinea','Eritrea','Eswatini','Ethiopia','Gabon','Gambia','Ghana','Guinea','Guinea-Bissau','Ivory Coast','Kenya','Lesotho','Liberia','Libya','Madagascar','Malawi','Mali','Mauritania','Mauritius','Morocco','Mozambique','Namibia','Niger','Nigeria','Rwanda','Sao Tome and Principe','Senegal','Seychelles','Sierra Leone','Somalia','South Africa','South Sudan','Sudan','Tanzania','Togo','Tunisia','Uganda','Zambia','Zimbabwe'],
 Asia:['Afghanistan','Armenia','Azerbaijan','Bahrain','Bangladesh','Bhutan','Brunei','Cambodia','China','Cyprus','Georgia','India','Indonesia','Iran','Iraq','Israel','Japan','Jordan','Kazakhstan','Kuwait','Kyrgyzstan','Laos','Lebanon','Malaysia','Maldives','Mongolia','Myanmar','Nepal','North Korea','Oman','Pakistan','Palestine','Philippines','Qatar','Saudi Arabia','Singapore','South Korea','Sri Lanka','Syria','Tajikistan','Thailand','Timor-Leste','Turkey','Turkmenistan','United Arab Emirates','Uzbekistan','Vietnam','Yemen'],
 Europe:['Albania','Andorra','Austria','Belarus','Belgium','Bosnia and Herzegovina','Bulgaria','Croatia','Czechia','Denmark','Estonia','Finland','France','Germany','Greece','Hungary','Iceland','Ireland','Italy','Kosovo','Latvia','Liechtenstein','Lithuania','Luxembourg','Malta','Moldova','Monaco','Montenegro','Netherlands','North Macedonia','Norway','Poland','Portugal','Romania','Russia','San Marino','Serbia','Slovakia','Slovenia','Spain','Sweden','Switzerland','Ukraine','United Kingdom','Vatican City'],
 'North America':['Antigua and Barbuda','Bahamas','Barbados','Belize','Canada','Costa Rica','Cuba','Dominica','Dominican Republic','El Salvador','Grenada','Guatemala','Haiti','Honduras','Jamaica','Mexico','Nicaragua','Panama','Saint Kitts and Nevis','Saint Lucia','Saint Vincent and the Grenadines','Trinidad and Tobago','United States'],
 'South America':['Argentina','Bolivia','Brazil','Chile','Colombia','Ecuador','Guyana','Paraguay','Peru','Suriname','Uruguay','Venezuela'],
 Oceania:['Australia','Fiji','Kiribati','Marshall Islands','Micronesia','Nauru','New Zealand','Palau','Papua New Guinea','Samoa','Solomon Islands','Tonga','Tuvalu','Vanuatu'],
 Antarctica:[]};
const icons={Africa:'🌍',Asia:'🌏',Europe:'🌍','North America':'🌎','South America':'🌎',Oceania:'🌊',Antarctica:'🧊'};
function $(x){return document.querySelector(x)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function initNav(){ $('#year')?.append(document.createTextNode(new Date().getFullYear())); $('#menuBtn')?.addEventListener('click',()=>$('#mainNav').classList.toggle('open')); $('#authBtn')?.addEventListener('click',openAuth); sb.auth.getUser().then(({data})=>{if(data.user){$('#authBtn').textContent='Account';}})}
function renderContinents(){const el=$('#continents'); if(!el)return; el.innerHTML=Object.entries(continents).map(([c,cs])=>`<button class="continent" data-continent="${esc(c)}"><span>${icons[c]}</span><strong>${esc(c)}</strong><small>${cs.length?cs.length+' countries':'Research destination'}</small></button>`).join(''); el.addEventListener('click',e=>{let b=e.target.closest('[data-continent]');if(b)showCountries(b.dataset.continent)})}
function showCountries(c){const p=$('#countryPanel');p.classList.remove('hidden');const cs=continents[c];p.innerHTML=`<div class="panel-head"><div><span class="eyebrow">DESTINATION</span><h3>${esc(c)}</h3></div><button class="close-country" onclick="this.closest('.country-panel').classList.add('hidden')">×</button></div>${cs.length?'<div class="country-grid">'+cs.map(x=>`<button class="country" data-country="${esc(x)}">${esc(x)} <span>→</span></button>`).join('')+'</div>':'<p>Antarctica is shown as a continent destination. Contact us for specialized travel information.</p>'}`;p.querySelectorAll('.country').forEach(b=>b.onclick=()=>openRequest('tour',b.dataset.country))}
const fieldMap={ticket:[['from_location','From'],['destination','Destination'],['travel_date','Travel date','date'],['return_date','Return date','date'],['passengers','Passengers','number'],['travel_class','Travel class']],hotel:[['destination','Destination'],['check_in','Check-in','date'],['check_out','Check-out','date'],['guests','Guests','number'],['rooms','Rooms','number'],['hotel_preference','Hotel preference']],visa:[['nationality','Nationality'],['destination_country','Destination country'],['visa_type','Visa type'],['travel_date','Travel date','date']],tour:[['destination','Destination'],['travel_date','Travel date','date'],['travelers','Travelers','number'],['package_preference','Package preference']],umrah:[['travelers','Travelers','number'],['preferred_month','Preferred month'],['package_preference','Package preference']]};
function openRequest(type,pref=''){const m=$('#requestModal');m.classList.remove('hidden');$('#requestTitle').textContent=type[0].toUpperCase()+type.slice(1)+' Request';const f=$('#requestForm');f.type.value=type;$('#dynamicFields').innerHTML=(fieldMap[type]||[]).map(([n,l,t])=>`<input name="${n}" ${t?'type="'+t+'"':''} placeholder="${l}" ${pref&&n==='destination'?'value="'+esc(pref)+'"':''}>`).join('');$('#requestMsg').textContent=''}
function initRequests(){document.querySelectorAll('[data-request]').forEach(b=>b.onclick=()=>openRequest(b.dataset.request));$('#closeModal').onclick=()=>$('#requestModal').classList.add('hidden');$('#requestModal').addEventListener('click',e=>{if(e.target.id==='requestModal')e.currentTarget.classList.add('hidden')});$('#requestForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target), type=f.get('type');let obj=Object.fromEntries(f.entries());delete obj.type;obj.status='Pending';let table={ticket:'ticket_requests',hotel:'hotel_requests',visa:'visa_requests',tour:'tour_requests',umrah:'umrah_requests'}[type];const msg=$('#requestMsg');if(!table){msg.textContent='Invalid request type';return}const {error}=await sb.from(table).insert(obj);msg.textContent=error?'Could not submit. Please try again.':'Request submitted successfully. Our team will contact you.';if(!error)e.target.reset()}}
async function loadJobs(){const grid=$('#jobsGrid');if(!grid)return;let {data,error}=await sb.from('job_vacancies').select('*').eq('is_active',true).order('created_at',{ascending:false});if(error){grid.innerHTML='<div class="empty">Unable to load vacancies right now.</div>';return}window.CF.jobs=data||[];fillCountries();renderJobs();}
function fillCountries(){const s=$('#jobCountry');if(!s)return;[...new Set((CF.jobs||[]).map(x=>x.country).filter(Boolean))].sort().forEach(c=>s.insertAdjacentHTML('beforeend',`<option>${esc(c)}</option>`))}
function renderJobs(){const grid=$('#jobsGrid'),q=($('#jobSearch')?.value||'').toLowerCase(),c=$('#jobCountry')?.value||'';const rows=(CF.jobs||[]).filter(j=>(!c||j.country===c)&&(!q||[j.title,j.company_name,j.country,j.location].join(' ').toLowerCase().includes(q)));grid.innerHTML=rows.length?rows.map(j=>`<article class="job-card"><span class="pill">${esc(j.country)}</span><h3>${esc(j.title)}</h3><p><b>${esc(j.company_name||'Employer')}</b> · ${esc(j.location||'')}</p><p>${esc(j.description||'No description provided.')}</p><div class="job-meta"><span>${esc(j.salary||'Salary on request')}</span><span>${esc(j.employment_type||'Employment')}</span></div><button class="btn primary small" data-job="${j.id}">Express Interest</button></article>`).join(''):'<div class="empty">No active vacancies match your search.</div>';grid.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>openJobInterest(b.dataset.job));}
function openJobInterest(id){const j=(CF.jobs||[]).find(x=>String(x.id)===String(id));if(!j)return;const m=$('#requestModal');m.classList.remove('hidden');$('#requestTitle').textContent='Job Interest';$('#dynamicFields').innerHTML=`<input type="hidden" name="job_id" value="${j.id}"><input type="hidden" name="country" value="${esc(j.country)}"><input name="job_title_display" value="${esc(j.title)}" disabled>`;$('#requestForm').type.value='job';$('#requestMsg').textContent='';$('#requestForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),obj=Object.fromEntries(f.entries());delete obj.type;delete obj.job_title_display;obj.status='Pending';const {error}=await sb.from('job_interest_requests').insert(obj);$('#requestMsg').textContent=error?'Could not submit. Please try again.':'Interest submitted successfully.';if(!error)e.target.reset()}}
function initJobFilters(){$('#jobSearch')?.addEventListener('input',renderJobs);$('#jobCountry')?.addEventListener('change',renderJobs)}
function openAuth(){const m=$('#authModal');if(m)m.classList.remove('hidden')}
function initAuth(){let signup=false;$('#closeAuth')?.addEventListener('click',()=>$('#authModal').classList.add('hidden'));$('#toggleAuth')?.addEventListener('click',()=>{signup=!signup;$('#authTitle').textContent=signup?'Sign up':'Login';$('#authSubmit').textContent=signup?'Create account':'Login';$('#fullNameAuth').style.display=signup?'block':'none';$('#toggleAuth').textContent=signup?'Already have an account? Login':'Create an account';});$('#authForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),email=f.get('email'),password=f.get('password'),msg=$('#authMsg');let r;if($('#authTitle').textContent==='Sign up')r=await sb.auth.signUp({email,password,options:{data:{full_name:f.get('full_name')}}});else r=await sb.auth.signInWithPassword({email,password});msg.textContent=r.error?r.error.message:'Success. Welcome!';if(!r.error)setTimeout(()=>location.href='admin.html',500)})}
async function initContact(){const f=$('#contactForm');if(!f)return;f.onsubmit=async e=>{e.preventDefault();const obj=Object.fromEntries(new FormData(f).entries());obj.status='New';const {error}=await sb.from('contact_messages').insert(obj);$('#contactMsg').textContent=error?'Could not send message.':'Message sent successfully.';if(!error)f.reset()}}
function boot(){initNav();renderContinents();initRequests();initAuth();initContact();initJobFilters();loadJobs()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
