const C=window.CF_CONFIG||{};
const countries={
 Africa:['Algeria','Angola','Benin','Botswana','Burkina Faso','Burundi','Cabo Verde','Cameroon','Central African Republic','Chad','Comoros','Congo','Democratic Republic of the Congo','Djibouti','Egypt','Equatorial Guinea','Eritrea','Eswatini','Ethiopia','Gabon','Gambia','Ghana','Guinea','Guinea-Bissau','Ivory Coast','Kenya','Lesotho','Liberia','Libya','Madagascar','Malawi','Mali','Mauritania','Mauritius','Morocco','Mozambique','Namibia','Niger','Nigeria','Rwanda','São Tomé and Príncipe','Senegal','Seychelles','Sierra Leone','Somalia','South Africa','South Sudan','Sudan','Tanzania','Togo','Tunisia','Uganda','Zambia','Zimbabwe'],
 Asia:['Afghanistan','Armenia','Azerbaijan','Bahrain','Bangladesh','Bhutan','Brunei','Cambodia','China','Cyprus','Georgia','India','Indonesia','Iran','Iraq','Israel','Japan','Jordan','Kazakhstan','Kuwait','Kyrgyzstan','Laos','Lebanon','Malaysia','Maldives','Mongolia','Myanmar','Nepal','North Korea','Oman','Pakistan','Palestine','Philippines','Qatar','Saudi Arabia','Singapore','South Korea','Sri Lanka','Syria','Tajikistan','Thailand','Timor-Leste','Turkey','Turkmenistan','United Arab Emirates','Uzbekistan','Vietnam','Yemen'],
 Europe:['Albania','Andorra','Austria','Belarus','Belgium','Bosnia and Herzegovina','Bulgaria','Croatia','Czechia','Denmark','Estonia','Finland','France','Germany','Greece','Hungary','Iceland','Ireland','Italy','Kosovo','Latvia','Liechtenstein','Lithuania','Luxembourg','Malta','Moldova','Monaco','Montenegro','Netherlands','North Macedonia','Norway','Poland','Portugal','Romania','Russia','San Marino','Serbia','Slovakia','Slovenia','Spain','Sweden','Switzerland','Ukraine','United Kingdom','Vatican City'],
 'North America':['Antigua and Barbuda','Bahamas','Barbados','Belize','Canada','Costa Rica','Cuba','Dominica','Dominican Republic','El Salvador','Grenada','Guatemala','Haiti','Honduras','Jamaica','Mexico','Nicaragua','Panama','Saint Kitts and Nevis','Saint Lucia','Saint Vincent and the Grenadines','Trinidad and Tobago','United States'],
 'South America':['Argentina','Bolivia','Brazil','Chile','Colombia','Ecuador','Guyana','Paraguay','Peru','Suriname','Uruguay','Venezuela'],
 Oceania:['Australia','Fiji','Kiribati','Marshall Islands','Micronesia','Nauru','New Zealand','Palau','Papua New Guinea','Samoa','Solomon Islands','Tonga','Tuvalu','Vanuatu'],
 Antarctica:['Antarctica']
};
const continentImages={Africa:'photo-1516026672322-bc52d61a55d5',Asia:'photo-1535139262971-c51845709a48',Europe:'photo-1499856871958-5b9627545d1a','North America':'photo-1485738422979-f5c462d49f74','South America':'photo-1483729558449-99ef09a8c325',Oceania:'photo-1506973035872-a4ec16b8e8d3',Antarctica:'photo-1517783999520-f068d7431a60'};
const teamProfiles={founder:['MD Easin Arafat','Founder & Managing Director','Founder and Managing Director of Continental Flyway. This role leads the company direction, strategic priorities and overall business development.'],cofounder:['Sahanul Islam','Co-Founder','Co-Founder of Continental Flyway, supporting the company’s development, partnerships and long-term initiatives.'],ceo:['Bahalul Islam','Chief Executive Officer','Chief Executive Officer, supporting executive operations, service delivery and organizational coordination.']};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
$('#year').textContent=new Date().getFullYear();
$('.nav-toggle').onclick=()=>$('#nav').classList.toggle('open');
$$('.nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));
$$('[data-service]').forEach(a=>a.addEventListener('click',()=>{const s=a.dataset.service;if(s) $('#serviceType').value=s}));
const continentGrid=$('#continentGrid');
for(const [name,list] of Object.entries(countries)){const card=document.createElement('article');card.className='continent';card.style.backgroundImage=`url('https://images.unsplash.com/${continentImages[name]}?auto=format&fit=crop&w=900&q=80')`;card.innerHTML=`<div class="continent-content"><h3>${name}</h3><span>${list.length} destination${list.length===1?'':'s'} • Explore countries →</span></div>`;card.onclick=()=>showCountries(name,list);continentGrid.appendChild(card)}
function showCountries(name,list){$('#modalContent').innerHTML=`<span class="kicker">DESTINATION GUIDE</span><h3>${name}</h3><p>Explore countries in ${name} and use the request form when you are ready to plan.</p><div class="country-list">${list.map(c=>`<button class="country-pill" data-country="${c}">${c}</button>`).join('')}</div>`;openModal();$$('.country-pill').forEach(b=>b.onclick=()=>{$('#request').scrollIntoView({behavior:'smooth'});$('#serviceType').value='tour';$('#modal').classList.remove('show')})}
function openModal(){$('#modal').classList.add('show')}$('.modal-close').onclick=()=>$('#modal').classList.remove('show');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('show')};
$$('.profile-btn').forEach(b=>b.onclick=()=>{const p=teamProfiles[b.dataset.profile];$('#modalContent').innerHTML=`<span class="kicker">LEADERSHIP</span><h3>${p[0]}</h3><b>${p[1]}</b><p>${p[2]}</p>`;openModal()});
const supabaseReady=()=>C.SUPABASE_PUBLISHABLE_KEY && !C.SUPABASE_PUBLISHABLE_KEY.includes('PASTE_');
const sb=supabaseReady()?window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY):null;
let jobs=[];
async function loadJobs(){if(!sb){renderJobs([]);return}const {data,error}=await sb.from('job_vacancies').select('*').eq('is_active',true).order('created_at',{ascending:false});if(!error)jobs=data||[];renderJobs(jobs);populateCountries()}
function populateCountries(){const s=$('#jobCountry');[...new Set(jobs.map(j=>j.country).filter(Boolean))].sort().forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;s.appendChild(o)})}
function renderJobs(items){const q=($('#jobSearch').value||'').toLowerCase(),c=$('#jobCountry').value;const filtered=items.filter(j=>(!q||`${j.title} ${j.country} ${j.location}`.toLowerCase().includes(q))&&(!c||j.country===c));$('#jobGrid').innerHTML=filtered.length?filtered.map(j=>`<article class="job-card"><span class="tag">${j.country||'International'}</span><h3>${esc(j.title)}</h3><p>📍 ${esc(j.location||'Location to be confirmed')}</p><p>🏢 ${esc(j.company_name||'Employer')}</p><p>💼 ${esc(j.employment_type||'Employment opportunity')}</p><button class="btn btn-primary interest" data-job="${j.id}">Express interest</button></article>`).join(''):`<div class="empty">${sb?'No matching vacancies are available right now.':'Connect your Supabase publishable key to load live vacancies.'}</div>`;$$('.interest').forEach(b=>b.onclick=()=>{location.hash='request';setTimeout(()=>{$('#serviceType').value='tour';$('#requestForm').dataset.job=b.dataset.job;$('#request').scrollIntoView({behavior:'smooth'})},50)})}
$('#jobSearch').oninput=()=>renderJobs(jobs);$('#jobCountry').onchange=()=>renderJobs(jobs);loadJobs();
$('#requestForm').addEventListener('submit',async e=>{e.preventDefault();const status=$('#formStatus');status.className='';status.textContent='Sending…';const f=new FormData(e.currentTarget),type=f.get('serviceType')||$('#serviceType').value;const common={full_name:f.get('full_name'),phone:f.get('phone'),email:f.get('email')||null,message:f.get('message')||null};let table,payload={...common};if(type==='ticket'){table='ticket_requests';payload={...payload,from_location:'',destination:f.get('destination'),travel_date:f.get('travel_date')||null,passengers:Number(f.get('count')||1)}}else if(type==='hotel'){table='hotel_requests';payload={...payload,destination:f.get('destination'),check_in:f.get('travel_date')||null,guests:Number(f.get('count')||1)}}else if(type==='visa'){table='visa_requests';payload={...payload,destination_country:f.get('destination'),travel_date:f.get('travel_date')||null}}else if(type==='umrah'){table='umrah_requests';payload={...payload,travelers:Number(f.get('count')||1),preferred_month:f.get('travel_date')||null}}else{table='tour_requests';payload={...payload,destination:f.get('destination'),travel_date:f.get('travel_date')||null,travelers:Number(f.get('count')||1)}}if(!sb){status.className='error';status.textContent='Supabase key is not configured yet.';return}const {error}=await sb.from(table).insert(payload);if(error){status.className='error';status.textContent='Could not submit. Please check the form and try again.';console.error(error);return}e.currentTarget.reset();$('#serviceType').value=type;status.className='success';status.textContent='Request submitted successfully.';showToast('Thank you. Your request has been received.')});
function showToast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),3500)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
